### ISSUE TITLE
log can not format

### ISSUE THREAD

**Issue by jinfagang** [abseil/abseil-py#125] opened 2019-12-03 02:54 UTC
I am really confusing right now:

```
from absl import logging as logger
import logging


fmt = '[%(levelname)s %(asctime)s %(filename)s:%(lineno)s] %(message)s'
formatter = logging.Formatter(fmt)

logger.get_absl_handler().setFormatter(formatter)
logger.set_verbosity('debug')

a = 3434
logger.info('{}'.format(a))

```

Doesn't applied format........... it prints 

```
INFO:absl:3434

```

I want line number and filename time etc....

**Comment by yilei** [comment] 2019-12-03 04:42
Closing as a duplicate of https://github.com/abseil/abseil-py/issues/124.

**Closed by yilei** 2019-12-03 04:42 UTC
